@startuml
'https://plantuml.com/class-diagram'
abstract class Vehiculo{
    {abstract}atravesarCasilla(Casillero c)
    mover(String direccion, Mapa mapa)
    aplicarMovs(int penalizacion)
}
class CuatroPorCuatro{
     atravesarCasilla(Casillero c)
     aplicarMovsPozo(int penalizacion)
}
class Moto{
     atravesarCasilla(Casillero c) {
}
class Auto{
    atravesarCasilla(Casillero c)
}
class Posicion{
    fila : int
    columna : int
    actualizarPosicion(String direccion)
    calcularPosicion(String direccion)
}

interface Casillero{
    aplicarMovimientosExtra(Vehiculo vehiculo)
}
class Mapa{
    tablero : Casillero
    dimension : int
    asignarCasillero(Casillero casillero, Posicion pos)
    obetenerCasilla(Posicion posicion)
    verificarPosicionValida(Posicion pos)
}

class Pozo implements Casillero{
    aplicarMovimientosExtra(Vehiculo vehiculo))
}
class SinObstaculo implements Casillero{
    aplicarMovimientosExtra((Vehiculo vehiculo)
}

class MovFactory{
    {static}MovimientoConstruir(String direccion)
}

interface Movimiento{
    moverFila(int columna)
    moverColumna(int fila)
}
class MovArriba implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovAbajo implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovDerecha implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovIzquierda implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}

Mapa *-- "*" Casillero
Moto --|> Vehiculo
Auto --|> Vehiculo
CuatroPorCuatro --|> Vehiculo
Vehiculo ..> Mapa
Vehiculo *--Posicion

MovFactory "crea"..> Movimiento

Posicion "utiliza"..> MovFactory

@enduml