@startuml
'https://plantuml.com/class-diagram'
abstract class Vehiculo{
    # posicion : Posicion
    {abstract}atravesarCasilla(Casillero c)
    mover(Movimiento movimiento)
    estaEnPosicion(Posicion posicionAComparar)
    {abstract}}Efecto aceptar(ElementoTablero elemento)
}
class CuatroPorCuatro{
    Efecto aceptar(ElementoTablero elemento)
}
class Moto{
    Efecto aceptar(ElementoTablero elemento)
}
class Auto{
    Efecto aceptar(ElementoTablero elemento)
}
class Posicion{
    - fila : int
    - columna : int
    actualizarPosicion(String direccion)
    calcularPosicion(String direccion)
}

class Casillero{
    - elementos : ElementoTablero
    atravesar(Vehiculo vehiculo)
    agregarElemento(ElementoTablero elemento)
}

class Efecto{
    - AplicadorDeMovimientos : aplicador
    - Vehiculo : vehiculo
    actualizar(int movimientosActuales)
    Vehiculo cambiar()
}

class Mapa{
    - grilla : Casillero
    - alto : int
    - ancho : int
    asignarCasillero(Casillero casillero, Posicion pos)
    obetenerCasilla(Posicion posicion)
    verificarPosicionValida(Posicion pos)
}

interface ElementoTablero{
    Efecto interactuar(Moto moto);
    Efecto interactuar(Auto auto);
    Efecto interactuar(Cuatroporcuatro cuatroporcuatro);
}

class Pozo implements ElementoTablero{
    Efecto interactuar(Auto auto)
    Efecto interactuar(Moto moto)
    Efecto interactuar(Cuatroporcuatro cuatroporcuatro)
}
class Piquete implements ElementoTablero{
    Efecto interactuar(Auto auto)
    Efecto interactuar(Moto moto)
    Efecto interactuar(Cuatroporcuatro cuatroporcuatro)
}

class SorpresaFavorable implements ElementoTablero{
}
class SorpresaDesfavorable implements ElementoTablero{
}
class SorpresaCambioVehiculo implements ElementoTablero{
}

interface Movimiento{
    - cantMovimientos : int
    moverFila(int columna)
    moverColumna(int fila)
}
class MovArriba implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovAbajo implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovDerecha implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}
class MovIzquierda implements Movimiento{
    int : cantMovimientos
    int moverColumna(int columna)
    int moverFila(int columna)
}

class Jugador{
    vehiculo : Vehiculo
    cantMovimientos : int
    estaEnPosicion(Posicion unaPosicion)
    cantidadDeMovimientosEs(int unEntero)
    mover(Movimiento movimiento)
}

Mapa *--"*" Casillero
Moto --|> Vehiculo
Auto --|> Vehiculo
CuatroPorCuatro --|> Vehiculo
Vehiculo ..> Mapa
Vehiculo *--Posicion

Jugador "crea"..> Movimiento

Casillero o--> ElementoTablero
Jugador *-->"1" Vehiculo
Jugador "utiliza"..> Efecto
Vehiculo "utiliza"..->Efecto
@enduml